--- #YAML:1.0
name:                Math-Business-BlackScholes
version:             1.01
abstract:            Black-Scholes option price model functions
license:             ~
author:              
    - Anders Johnson <anders@ieee.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Math::CDF:                     0.1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
